### ISSUE TITLE
Data parser 

### ISSUE THREAD

**Issue by etoumey** [etoumey/bodyStats#1]
Incorporate latest week's data into the data file.

**Comment by jtoumey** [comment]
I created a file called `parseCSV` that can contain the tools to parse various _*.csv_ files. We have to decide how much flexibility and error checking we want in these functions. 

There is a very basic RHR parser in there right now. No error checking, hard-coded sample file, etc. 

Once we bring in all of the data from the various "new" weekly files, we need to open the "database" file, do the comparison of recent dates (to avoid overlap), and store the new information while accounting for dates that do not have any data.

P.S. @etoumey, could you paste a weekly RHR file where one of the days is missing data? I am not sure i have any...

**Comment by etoumey** [comment]
added missing data .csv

**Comment by etoumey** [comment]
whoops. Forgot parseCSV existed. It is much cleaner than what I just wrote. I may merge it in. Main difference is mine uses csv.reader(). Both need to add validation for missing days. I am going to close this issue, but open a different one on editing the parser to behave when there's a missed day.
