### ISSUE TITLE
Planning for 2.0

### ISSUE THREAD

**Issue by jtoumey** [etoumey/bodyStats#15]
@etoumey 

Maybe we can try this out. At least we can have structured replies and tag each other.

I see a few parts to figure out: 
1. Managing a database of health data.
2. Fast and robust analysis of the data (averages, maximums, std deviations, etc over user-specified ranges).
3. ML models to detect correlations.
4. Ability to scrape data from Garmin Connect. (To start, we can maintain a dummy database with like a _*.csv_ file to get things working.)

What are you thinking?

**Comment by jtoumey** [comment]
Oh god, sorry about the spam.

**Comment by etoumey** [comment]
Okay, selenium looks like the way to go on data scraping. I am working on actually getting to the export page. Login is achieved by opening a file called `credentials.pass` in the selenium directory containing 
`username@gmail.com`
`pA55W0rD`
I added .pass to the gitignore so hopefully that never slips into the flow. I'm thinking we just append the database with un-scraped data. So maybe the head of the database will be the most recent date scraped?

**Comment by jtoumey** [comment]
One option we have for non-development versions is to prompt the user to supply credentials in the terminal.

**Comment by etoumey** [comment]
Still some good items to put into 3.0
