### ISSUE TITLE
Develop database structure

### ISSUE THREAD

**Issue by jtoumey** [etoumey/bodyStats#16]
@etoumey 
I don't know what the best structure is for storing the data. I am sure we could connect to a python module that has some optimized database thing. Also, we could just use an existing data structure in Python. 

We run the program only occasionally, so of course data is destroyed whenever the app closes. So we need to store in an external file, right? That is flexible -- we can start with ASCII (csv) and eventually do something like a binary file if it gets too big

Every time the app runs, it need to read the database file. The dummy code I wrote [here](https://github.com/etoumey/bodyStats/blob/master/healthStats/healthStats.py) reads the csv file and puts the data into a python `dictionary`  data structure where the 'key' to retrieve data is a data code (`YYYYMMDD`). 

It would be possible to expand on that method, or take a different approach.

**Comment by jtoumey** [comment]
The database should be a stand-alone class. Member functions can include things like `update` to pull and integrate new data from g.connect, `initialLoad` to initiate the database for the first time, and functions to show and analyze data.

**Comment by etoumey** [comment]
I would like to use JSON. It is current standard in tripy. I see tripy being incorporated into bodystats and it would be nice to have a PMC JSON and bodystat JSON. They could even be merged. I modified the module diagram to include where i think tripy should be called. I will read through what has already been written in Jun 2018 to make sure this is the best way forward. Closing now with the resolution to use json.

**Comment by etoumey** [comment]
I am again researching SQLite. I have decided I'm not happy with the json implementation in tripy.

**Comment by etoumey** [comment]
SQL is actually really helpful and eliminates a lot of the annoying logic that is in tripy. I am using SQLite browser from https://sqlitebrowser.org/ and that makes the whole thing a lot less intimidating because it's easy to actually see the data.

**Comment by etoumey** [comment]
Conversion to SQL is almost complete. The only lingering issue is adapting the process log to SQL

**Comment by etoumey** [comment]
Separate issue for process log SQLite integration. Closing.
