### ISSUE TITLE
Merge runStats

### ISSUE THREAD

**Issue by npbassett** [etoumey/bodyStats#39]
Add plotting capabilities for activity data.

**Comment by etoumey** [comment]
Can you put some more detail in this issue.

**Comment by npbassett** [comment]
So far all I've done over at runStats is a script for plotting cumulative miles over time for multiple years. I've been using the bulk CSV export file from [https://connect.garmin.com/modern/activities](url). Right now I believe bodyStats just downloads individual gpx files for each activity, do you think you could work on automating the download of the csv file as well? You have more experience with selenium than I do.

**Comment by etoumey** [comment]
Okay. Here's an idea. Download and parse the GPX and save the important stats to the database. Like miles run, average HR, etc. Then you can run a query on the database for total miles over any period of time?

I don't like the idea of redundantly downloading the CSV file when the information should have already been fetched on a per-activity basis. Thoughts?

**Comment by npbassett** [comment]
Not sure I understand the benefit of downloading and parsing the GPX file for each activity over just downloading the CSV.

**Comment by etoumey** [comment]
The benefit is the TRIMP score. You can't calculate that with the CSV. That's the whole point of the tripy module. To get chronic training load and acute training load.

**Comment by etoumey** [comment]
@npbassett what is the status of this issue?

**Comment by npbassett** [comment]
Everything is now in plot.py
